### ISSUE TITLE
API response can't be parsed.

### ISSUE THREAD

**Issue by Pheggas** [aunefyren/wrapperr#11]
Just fired up docker compose container containing Plex Wrapped (small tweak with outside port of 8090 as the port 80 was already in use), configured it via web UI.

Good to know: I have two instances of tautulli (one in docker via docker-compose and one outside of docker like "on bare metal").

Plex Wrapped didn't even accept tautulli's (instance that is on bare metal) API so i tried one that's dockerized. When i clicked the test button, it didn't turn red which is... good i think? 
Then i saved it, configured the timeline i want to wrap and tried to enter my email adress. After some time of sand clock animation it just thrown error in the title.

in `docker logs` there were only POST and GET requests...

Any idea how to fix this?

**Comment by aunefyren** [comment]
This sounds tricky, we need to isolate the problem. As Plex-Wrapped is running in a container, it needs a way to connect to Tautulli, wether that is by connecting to the Docker host directly, or by connecting to another container using the Docker network. When I am troubleshooting stuff like this is typically enter the cointainer and try to curl the services I am trying to connect to (might have to install curl when inside). Like this:
```
$ docker exec -it plex-wrapped /bin/bash
$ curl http://192.168.1.150/tautulli
```
If the container can't reach Tautulli, neither can Plex-Wrapped. Test if you can reach the different Tautulli server from the Plex-Wrapped container. To check what the errors you get are, check the devloper console for your web browser or try using the api directly at `http://<your-plex-wrapped>/api/get_stats.php?p_identity=<username-or-email>`.

Here is an example of two different containers that can use internal Docker networking to connect to each other. The IP of the container can be found using `docker inspect <container-name>`. Because they share the same network named 'wrapped', they can connect using their container IP. Typically 172.20.X.X:

```
version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "/media/CASE/Nginx:/etc/nginx/conf.d"
    #  - "/media/CASE/Nginx/html:/var/www/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - PUID=1000
      - PGID=1000
    networks:
      - wrapped
  wrapped:
    image: aunefyren/plex-wrapped:latest
    container_name: wrapped
    expose:
      - "80"
    networks:
      - wrapped
networks:
  wrapped:
```

The easiest way to fix a container not reaching another container is using `network_mode: host` in the docker-compose.yml in my opinion. This only works on Linux though. If you use host then the IP and ports of the container will be shared by the host.

**Comment by Pheggas** [comment]
Thank you for detailed description. I tried to access the API directly. Unfortunately, without luck. It simply didn't want to respond at all. I also tried the first way via `docker exec` but with dockerized tautulli, i got error with that app is unreachable. Tried bare metal tautulli as well and it wrote it is reachable but nothing much else. 

Finally, i added `network_mode: host` but it didn't like i set ports for that container (which is reasonable), so i tried to get into config.json via docker exec but in there, there's no vim or nano. Simply something with what i could edit that file.

At this point i'm writting this comment. I might try removing port mapping from compose.yml but i assume it wouldn't work according to fact, that port is already used. Any other way to change the port directly in config.json?

**Comment by aunefyren** [comment]
Okay, so I am a bit confused, so I will try to be clear. Not easy to do this over text, haha.

> I tried to access the API directly. Unfortunately, without luck. It simply didn't want to respond at all.

I assume this means the HTTP for the entire website doesn't load. This means Plex-Wrapped could be working, but you can't connect to it.

> I also tried the first way via docker exec but with dockerized tautulli, i got error with that app is unreachable. Tried bare metal tautulli as well and it wrote it is reachable but nothing much else.

Okay, so you entered the Plex-Wrapped container and curled the different Tautulli servers, with no response. All of this points to the container being unable to connect to your network, just like I mentioned earlier. 

> Finally, i added network_mode: host but it didn't like i set ports for that container (which is reasonable), so i tried to get into config.json via docker exec but in there, there's no vim or nano. Simply something with what i could edit that file.

Yes, when you add `network_mode: host` to a service in Docker-compose, it says you have to remove the `-port:` settings. Not sure why you entered the container to edit the config.json, as the Docker-compose is reffering to your docker-compose.yml, not Plex Wrappeds settings. (Btw, when inside the container you can install missing packages, such as VIM or Nano using `apt-get update` and then `apt-get install nano`).

Here is a docker-compose with the port settings removed:

```
version: '3'
services:
  wrapped:
    image: aunefyren/plex-wrapped:latest
    container_name: wrapped
    network_mode: host
```
