### ISSUE TITLE
Issue, Wrapperr is not configured on new docker pull

### ISSUE THREAD

**Issue by ItsM3rry** [aunefyren/wrapperr#42]
Hi,

Each time I pull a new version of docker image and I restart my container the config is totally wiped and I have to totally reconfigure it

Here's my compose : 

```
version: '3.3'
services:
  wrapperr:
    ports:
      - '8282:8282'
    container_name: wrapperr
    image: 'aunefyren/wrapperr:latest'
    volumes:
      - './config:/var/www/html/config'
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
    healthcheck:
     test: ["CMD-SHELL", "curl --connect-timeout 15 --silent --show-error --fail http://127.0.0.1:8282 || exit 1"]
     interval: 1m30s
     timeout: 10s
     retries: 3
```

With `docker exec chmod 0777 ./config`
My log file wrapped.log is empty btw
