### ISSUE TITLE
Container crashes after downloading an arbitrary number of days from Tautulli, error message displays "API response can't be parsed." 

### ISSUE THREAD

**Issue by ASK-ME-ABOUT-LOOM** [aunefyren/wrapperr#83]
When updating wrapper to run this year (I'd love to have a box that says "always get the last 12 months," I sent out a link to it and forgot entirely I'd have to go into the admin panel and update the timeframe) I see that it downloads a number of days worth of tautulli data, at which point the container crashes and the main page displays "API response can't be parsed." 

I can't otherwise find any useful logs. It seems able to talk to tautulli with no issue. Sometimes it downloads one day's worth of logs and then crashes. Other times it downloads 8 or 9 months of days and then crashes. Example output:

```
wrapperr  | Log file set.
wrapperr  | 2023/12/12 07:08:14 Timezone set to America/New_York.
wrapperr  | 2023/12/12 07:08:14 Running version v3.2.2.
wrapperr  | 2023/12/12 07:08:14 Starting Wrapperr on port 8282.
wrapperr  | 2023/12/12 07:08:14 Starting using HTTP.
wrapperr  | 2023/12/12 07:08:43 Retrieved Wrapperr functions. - Origin: 127.0.0.1
wrapperr  | [GIN] 2023/12/12 - 07:08:43 | 200 |    1.716091ms |       127.0.0.1 | POST     "/api/get/functions"
wrapperr  | 2023/12/12 07:08:43 New wrap request.
wrapperr  | 2023/12/12 07:08:43 Checking Tautulli server 'tautulli'.
wrapperr  | 2023/12/12 07:08:43 Getting users from Tautulli server 'tautulli'.
wrapperr  | 2023/12/12 07:08:43 Getting stats for: username
wrapperr  | 2023/12/12 07:08:43 Cache stage completed for username.
wrapperr  | 2023/12/12 07:08:43 Checking Tautulli server 'tautulli'.
wrapperr  | 2023/12/12 07:08:43 Downloading day: 2022-12-31 from server 'tautulli'.
wrapperr  | 2023/12/12 07:08:44 Downloading day: 2023-01-01 from server 'tautulli'.
wrapperr  | 2023/12/12 07:08:44 Downloading day: 2023-01-02 from server 'tautulli'.
wrapperr  | 2023/12/12 07:08:44 Downloading day: 2023-01-03 from server 'tautulli'.
[ ...snip... ]
wrapperr  | 2023/12/12 07:09:24 Downloading day: 2023-06-23 from server 'tautulli'.
wrapperr  | 2023/12/12 07:09:24 Downloading day: 2023-06-24 from server 'tautulli'.
wrapperr  | 2023/12/12 07:09:25 Downloading day: 2023-06-25 from server 'tautulli'.
wrapperr exited with code 0
```

There are no other meaningful logs I can find. Tautulli isn't reporting anything odd on its side, either.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
My docker-compose.yml, if it is helpful:

```
---
version: '3.3'
services:
  wrapperr:
    environment:
      - TZ=America/New_York
    container_name: wrapperr
    image: aunefyren/wrapperr:latest
    restart: always
    volumes:
      - './config:/app/config'
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
    networks:
      - backend
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 8282 || exit 1']
      interval: 2s
      timeout: 1s
      retries: 10

networks:
  backend:
    external: true
```
